import type { Metadata } from "next";
import { Zain, Commissioner, Shippori_Antique_B1 } from "next/font/google";
import "./globals.css";

const zain = Zain({
  weight: ["200", "300", "400", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-zain",
});

const shippori = Shippori_Antique_B1({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-shippori",
});

const commissioner = Commissioner({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-commissioner",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${zain.variable} ${commissioner.variable} ${shippori.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
